# Generated by Django 6.1.1 on 2026-09-23 04:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Term 1', max_length=50)),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Al-Wasilah School Complex', max_length=255)),
                ('motto', models.CharField(default='Knowledge, Virtue & Excellence', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('current_academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('current_term', models.CharField(default='Term 1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('class_level', models.CharField(choices=[('creche', 'Creche'), ('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('kg_1', 'KG 1'), ('kg_2', 'KG 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jhs_1', 'JHS 1'), ('jhs_2', 'JHS 2'), ('jhs_3', 'JHS 3')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('class_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='portal.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_billed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='portal.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('class_assigned', models.CharField(blank=True, choices=[('creche', 'Creche'), ('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('kg_1', 'KG 1'), ('kg_2', 'KG 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jhs_1', 'JHS 1'), ('jhs_2', 'JHS 2'), ('jhs_3', 'JHS 3')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
