# Generated by Django 6.1.1 on 2026-09-23 04:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradereport',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_id',
            new_name='index_number',
        ),
        migrations.AddField(
            model_name='gradereport',
            name='credit_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='grade',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='subject_code',
            field=models.CharField(default='SUB101', max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='total_mark',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fee_category',
            field=models.CharField(default='REGULAR', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(default='GHANAIAN', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='program_name',
            field=models.CharField(default='BASIC EDUCATION', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='uin',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('BILLING', 'Billing'), ('PAYMENT', 'Payment')], max_length=10)),
                ('narration', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='portal.studentprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='FeeStatement',
        ),
    ]
