# Generated by Django 6.1.1 on 2026-09-23 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_subject_gradereport_subject_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradereport',
            name='credit_hours',
        ),
        migrations.RemoveField(
            model_name='schoolbranding',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent',
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='email',
            field=models.EmailField(default='alwasilaschool2026@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='phone_numbers',
            field=models.CharField(default='0244963410 / 0246849302 / 0243881080', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='postal_address',
            field=models.CharField(default='P.O.Box 161 TL', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='primary_color',
            field=models.CharField(default='#6b1d2f', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='secondary_color',
            field=models.CharField(default='#d4af37', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_contact',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/passports/'),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='motto',
            field=models.CharField(default='KNOWLEDGE, INTEGRITY AND EXCELLENCE', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='school_name',
            field=models.CharField(default='AL WASILAH SCHOOL COMPLEX', max_length=255),
        ),
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('class_level', models.CharField(blank=True, choices=[('creche', 'Creche'), ('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('kg_1', 'KG 1'), ('kg_2', 'KG 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jhs_1', 'JHS 1'), ('jhs_2', 'JHS 2'), ('jhs_3', 'JHS 3')], max_length=20, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=30, unique=True)),
                ('class_assigned', models.CharField(choices=[('creche', 'Creche'), ('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('kg_1', 'KG 1'), ('kg_2', 'KG 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jhs_1', 'JHS 1'), ('jhs_2', 'JHS 2'), ('jhs_3', 'JHS 3')], max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('age', models.IntegerField(default=25)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='teachers/passports/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
