# Generated by Django 6.1.1 on 2026-09-23 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_gradereport_credit_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradereport',
            name='term',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='student',
        ),
        migrations.RemoveField(
            model_name='schooldocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gradereport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gradereport',
            name='total_mark',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fee_category',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_contact',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='passport_photo',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='uin',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='passport_photo',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='gradereport',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_class',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_class',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='class_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='exam_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='current_academic_year',
            field=models.CharField(default='2026/2027', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='current_term',
            field=models.CharField(default='FIRST TRIMESTER', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='email',
            field=models.EmailField(blank=True, default='info@alwasilah.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='motto',
            field=models.CharField(default='Knowledge and Excellence', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='phone_numbers',
            field=models.CharField(blank=True, default='0240000000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='postal_address',
            field=models.CharField(blank=True, default='P.O. Box 123', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='primary_color',
            field=models.CharField(default='#1e7e34', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='secondary_color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='index_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
        migrations.DeleteModel(
            name='SchoolDocument',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
