# Generated by Django 6.1.1 on 2026-09-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_academicterm_gradereport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbranding',
            name='email',
            field=models.EmailField(blank=True, default='info@alwasilah.edu.gh', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='logo_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/120?text=Logo', null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='phone_numbers',
            field=models.CharField(blank=True, default='+233 24 000 0000 / +233 20 000 0000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='postal_address',
            field=models.CharField(blank=True, default='P.O. Box 123, Tamale', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='primary_color',
            field=models.CharField(default='#800020', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='school_name',
            field=models.CharField(default='AL-WASILAH SCHOOL COMPLEX', max_length=255),
        ),
    ]
