# Generated by Django 6.1.1 on 2026-09-27 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_schoolbranding_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('academic_year', models.CharField(max_length=20)),
                ('billing', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('narration', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortalBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Al-Wasilah Basic School', max_length=255)),
                ('motto', models.CharField(default='Excellence and Integrity', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#5c1825', max_length=20)),
                ('accent_color', models.CharField(default='#e6b800', max_length=20)),
                ('contact_email', models.EmailField(default='info@alwasilah.edu.gh', max_length=254)),
                ('contact_phone', models.CharField(default='+233 24 000 0000', max_length=50)),
                ('address', models.TextField(default='Tamale, Ghana')),
                ('current_academic_year', models.CharField(default='2026/2027', max_length=20)),
                ('current_term', models.CharField(default='FIRST TRIMESTER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('trimester', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=150)),
                ('credit_hours', models.IntegerField(default=3)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
        migrations.RemoveField(
            model_name='feeledger',
            name='student',
        ),
        migrations.RemoveField(
            model_name='gradereport',
            name='student',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='student',
        ),
        migrations.DeleteModel(
            name='SchoolBranding',
        ),
        migrations.RemoveField(
            model_name='schooldocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_class',
            field=models.CharField(default='Basic 1', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disability_status',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fee_category',
            field=models.CharField(default='REGULAR', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='index_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default='100', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default='GHANA', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='programme',
            field=models.CharField(default='BASIC EDUCATION', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FeeLedger',
        ),
        migrations.DeleteModel(
            name='GradeReport',
        ),
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
        migrations.DeleteModel(
            name='SchoolDocument',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
