# Generated by Django 6.1.1 on 2026-09-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_feeledgerentry_portalbranding_statementofresult_and_more'),
        ('portal', '0008_create_default_superuser'),
    ]

    operations = [
    ]
