# Generated by Django 6.1.1 on 2026-09-27 22:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_merge_20260927_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeledgerentry',
            old_name='billing',
            new_name='amount_due',
        ),
        migrations.RenameField(
            model_name='feeledgerentry',
            old_name='payment',
            new_name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='feeledgerentry',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='feeledgerentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feeledgerentry',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='portalbranding',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='portalbranding',
            name='current_academic_year',
        ),
        migrations.RemoveField(
            model_name='portalbranding',
            name='current_term',
        ),
        migrations.RemoveField(
            model_name='portalbranding',
            name='motto',
        ),
        migrations.RemoveField(
            model_name='portalbranding',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fee_category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_relationship',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uin',
        ),
        migrations.AddField(
            model_name='feeledgerentry',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeledgerentry',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeledgerentry',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeledgerentry',
            name='title',
            field=models.CharField(default='School Fees', max_length=200),
        ),
        migrations.AddField(
            model_name='portalbranding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_brand_portal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_picture',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='feeledgerentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_entries', to='portal.userprofile'),
        ),
        migrations.AlterField(
            model_name='portalbranding',
            name='contact_email',
            field=models.EmailField(default='info@alwasilah.edu', max_length=254),
        ),
        migrations.AlterField(
            model_name='portalbranding',
            name='contact_phone',
            field=models.CharField(default='+233 000 000 000', max_length=50),
        ),
        migrations.AlterField(
            model_name='portalbranding',
            name='school_name',
            field=models.CharField(default='Al-Wasilah School Complex', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_class',
            field=models.CharField(default='Primary 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='programme',
            field=models.CharField(default='General Studies', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('class_score', models.FloatField(default=0.0)),
                ('exam_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('academic_term', models.CharField(default='Term 1', max_length=50)),
                ('academic_year', models.CharField(default='2026/2027', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portal.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='StatementOfResult',
        ),
    ]
