# Generated by Django 6.1.1 on 2026-09-28 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_rename_billing_feeledgerentry_amount_due_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portalbranding',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='portalbranding',
            name='footer_text',
            field=models.CharField(default='Copyright © 2026 Al-Wasilah School Complex. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='portalbranding',
            name='primary_color',
            field=models.CharField(default='#800020', max_length=10),
        ),
        migrations.AddField(
            model_name='portalbranding',
            name='secondary_color',
            field=models.CharField(default='#17a2b8', max_length=10),
        ),
        migrations.AddField(
            model_name='portalbranding',
            name='tagline_subtext',
            field=models.CharField(default='Excellence in Academic & Moral Training', max_length=255),
        ),
        migrations.AlterField(
            model_name='portalbranding',
            name='address',
            field=models.TextField(default='Tamale, Northern Region, Ghana'),
        ),
        migrations.AlterField(
            model_name='portalbranding',
            name='contact_email',
            field=models.EmailField(default='info@alwasilah.edu.gh', max_length=254),
        ),
        migrations.AlterField(
            model_name='portalbranding',
            name='contact_phone',
            field=models.CharField(default='+233 24 000 0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='portalbranding',
            name='school_name',
            field=models.CharField(default='AL-WASILAH SCHOOL COMPLEX', max_length=255),
        ),
        migrations.CreateModel(
            name='FeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=20)),
                ('index_number', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_class', models.CharField(default='Primary 1', max_length=50)),
                ('programme', models.CharField(default='BASIC EDUCATION CURRICULUM', max_length=100)),
                ('gender', models.CharField(default='MALE', max_length=10)),
                ('passport_picture', models.ImageField(blank=True, null=True, upload_to='passports/')),
                ('can_brand_portal', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FeeLedgerEntry',
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
