# Generated by Django 6.1.1 on 2026-09-28 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_studentresult_student_remove_userprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeledger',
            name='academic_year',
            field=models.CharField(default='2026/2027', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='generated_password',
            field=models.CharField(default='ChangeMe123!', max_length=100),
        ),
        migrations.CreateModel(
            name='AcademicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('class_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('academic_term', models.CharField(default='Term 1', max_length=50)),
                ('academic_year', models.CharField(default='2026/2027', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
