# Generated by Django 6.1.1 on 2026-09-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_feeledger_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresult',
            name='position_in_subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
