# Generated by Django 6.1.1 on 2026-09-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_academicresult_position_in_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_role', models.CharField(default='all', max_length=20)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='feeledger',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='conduct_rating',
            field=models.CharField(default='GOOD', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='days_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='teacher_remarks',
            field=models.TextField(default='Satisfactory progress made. Keep working hard.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_school_days',
            field=models.IntegerField(default=60),
        ),
    ]
