# Generated by Django 6.1.1 on 2026-09-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_announcement_feeledger_receipt_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portalbranding',
            old_name='footer_text',
            new_name='footer_copyright',
        ),
        migrations.AddField(
            model_name='portalbranding',
            name='navbar_style',
            field=models.CharField(default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='portalbranding',
            name='sidebar_color',
            field=models.CharField(default='#1e2229', max_length=10),
        ),
        migrations.AlterField(
            model_name='portalbranding',
            name='tagline_subtext',
            field=models.CharField(default='Knowledge, Integrity and Excellence', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='teacher_remarks',
            field=models.TextField(default='Satisfactory academic performance. Keep working hard.'),
        ),
    ]
