# Generated by Django 6.1.1 on 2026-09-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_rename_footer_text_portalbranding_footer_copyright_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalbranding',
            name='navbar_style',
        ),
    ]
