# Generated by Django 6.1.1 on 2026-09-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_remove_portalbranding_navbar_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='Primary 1', max_length=50)),
                ('day_of_week', models.CharField(default='Monday', max_length=20)),
                ('period_time', models.CharField(default='08:00 - 09:00', max_length=50)),
                ('subject_name', models.CharField(default='Mathematics', max_length=100)),
                ('teacher_name', models.CharField(default='Madam Comfort', max_length=100)),
                ('venue', models.CharField(default='Classroom 1', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='portalbranding',
            name='login_background',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
